apiVersion: apps/v1
kind: Deployment
metadata:
  name: openshift-demo-deployment
  labels:
    app: openshift-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      project: openshift-demo
  template:
    metadata:
      labels:
        project: openshift-demo
    spec:
      containers:
        - name: openshift-demo
          image: openshift/hello-openshift:v3.9.0
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
