apiVersion: v1
kind: Service
metadata:
  name: openshift-demo-service
  labels:
    app: openshift-demo
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    project: openshift-demo
